### PR TITLE
Remove createClass. Add prop-types and react-creact-class

### PR DESCRIPTION
**Pull request by srallen**
This removes `React.createClass` and `React.PropTypes` to use the newer packages. I can't get the tests to run, so I'm not sure if this breaks anything. I think zuul is broken/an abandon project. The readme shows that the current build is failing: https://github.com/defunctzombie/zuul

### CODE REVIEW

**Comment by srallen** [comment]
Travis doesn't seem to have issues with it....

**Comment by eatyourgreens** [comment]
Changes look good to me on reading through the diff. Should we publish as a new minor version, then apps can roll back to the previous minor version if there are problems.

**Comment by srallen** [comment]
Sounds good to me. It should also be noted this does not bump React to version 16, so if that needs to happen, it probably should be in a separate PR.

**Comment by eatyourgreens** [comment]
Published as 2.5.0.

**Comment by tingard** [comment]
I don't think this has caught all instances of React.PropTypes https://github.com/zooniverse/modal-form/blob/master/dialog.js line 58

**Comment by srallen** [comment]
Ah, yes, that was missed. I'll get another PR up in a moment.

**Pull request merged**
