### PR TITLE
Upgrade to React 16

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade the dev environment to React 16.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks like React 16 breaks refs somehow. `this.form` is undefined after the sticky form mounts.

**Comment by eatyourgreens** [comment]
Examples are broken too, because they can't find `react.js` and `react-dom.js`.

**Comment by eatyourgreens** [comment]
Tested with React 16.2 and React 16.3. This is broken in both.

Tracing the component lifecycle, the component mounts, renders and calls `componentDidMount` before the ref callbacks run. `componenDidMount` calls `reposition`, which assumes that refs have been set.

**Comment by eatyourgreens** [comment]
[The solution here is probably to use portals](https://github.com/facebook/react/issues/12034#issuecomment-358465235), which turns out to be a bigger rewrite of the rendering and positioning code.

**Comment by srallen** [comment]
Thanks for tackling this. I'll try to take a look at this today.

**Comment by eatyourgreens** [comment]
Triggered forms are broken because clicks on the underlay are bubbling back up the tree to the trigger button, and re-opening the form when it closes. I thought portals trapped events but maybe not.

**Comment by eatyourgreens** [comment]
[Event bubbling to React ancestors](https://reactjs.org/docs/portals.html#event-bubbling-through-portals) is intended behaviour in React 16. If I understand Dan Abramov's explanation correctly, the triggered form is just badly coded in that it's a child of the trigger and should be a sibling.

**Comment by eatyourgreens** [comment]
@srallen Should be all fixed now. I'm thinking we should release this as 2.6.0, so we can leave the current version of PFE on 2.5, and upgrade the React 16 branch to 2.6.

**Comment by eatyourgreens** [comment]
THE TESTS ARE FINALLY PASSING.
Happy Isabelle from Animal Crossing.

**Comment by eatyourgreens** [comment]
This works with 16.3 or 16.2 and the new refs API is backward compatible with callback refs so nothing should break.

**Comment by eatyourgreens** [comment]
Published as 2.6.0.

**Pull request merged**
