### PR TITLE
Security updates

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrade packages via `npm audit fix`.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Updating zuul breaks the tests 😢.

**Comment by eatyourgreens** [comment]
`localtunnel.me` is unreliable, which is causing the test failures. See defunctzombie/zuul#251

**Comment by eatyourgreens** [comment]
So, I set the concurrent builds to 1 in Travis, for this repo, then just hit the rebuild button on failing builds until the tests ran. 🤷‍♂️

**Comment by srallen** [comment]
[phantom.js is also a dead project now](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE). I can't get packages to install. The phantom.js dependency install fails. We should probably remove zuul and phantom.js entirely. I'll give it a go to try getting jsdom working instead.

**Comment by srallen** [comment]
Looking over the tests, I don't think jsdom will be sufficient because there are some positioning tests and I think those will need rendering. Looking into puppeteer instead.

**Comment by srallen** [comment]
Or it'd probably work with JSDOM rewriting the tests to use enzyme.

**Comment by srallen** [comment]
Either one would potentially be a lot of work that I'm not sure is worth it since the API design of this library isn't great for what we mostly use it for. It might be worth looking for replacements. Grommet 2 components for modals, tooltips, or other libraries for those kinds of elements.

**Comment by eatyourgreens** [comment]
I'm going to close this in favour of removing zuul.

**Pull request closed without merging**
