### PR TITLE
Check for Modal Width Overflow

### LINKED ISSUE #30: Boundary Overflow on Mobile
On mobile views, iPhone, etc. the menu will overflow out of the viewport. 

screen shot 2017-05-22 at 11 46 57 am

### PR DESCRIPTION
**Pull request by wgranger**
Fixes #30 

This fixes the issue occurring with the main menu overflowing the width on mobile view.

Staged [here](https://modal-menu-overflow.pfe-preview.zooniverse.org/)

### CODE REVIEW

**Comment by srallen** [comment]
As an aside, if the automated tests aren't catching that the position calculation isn't correct for certain sticky/triggered modal positions, then there are gaps in our tests that need to be fixed.

**Comment by eatyourgreens** [comment]
I had a look at project tutorials on PFE using this branch. The tutorial does try to stay centred in the viewport, but becomes very jerky when you scroll down. The tutorial moves down with the page then jumps back up when the javascript updates the element position. This results in an unpleasant vertical jerking motion. Tested using Chrome on OSX.

`position: fixed` might be better if you want to fix an element within the viewport, but could be difficult to get working consistently across browsers, viewports etc.

**Comment by wgranger** [comment]
The first commit appeared to be using an item's width rather than the entire width of the screen, so that was adjusted with the most recent change. 

The repositioning calculations seemed to be correct, they just weren't taking into account that a modal could be off screen. A couple tests were written to account for this.

**Comment by wgranger** [comment]
The staged branch above has also been updated to reflect the most recent commit.

**Comment by wgranger** [comment]
@srallen A couple changes were made to this PR when you get a chance.

**Comment by wgranger** [comment]
Yep. I'll be able to get to that shortly.

**Comment by srallen** [comment]
OK, if you haven't done it before, there's a npm zooniverse user that you can authenticate as. Feel free to ask questions here on in the dev channels.

**Comment by wgranger** [comment]
@srallen Couple questions below.

I'm thinking my workflow is as follows, correct me if I'm wrong:
1) Merge this PR
2) `npm version patch` from updated master
3) `git push origin --tags`? or `git push origin master`. This repo doesn't use tags, so I don't believe the former is necessary.
4) `npm publish` Any idea where I can get the Zooniverse user info?

**Comment by srallen** [comment]
That's about right:
1. Merge, then checkout master and pull down the changes
2. `npm version patch` since this is a bugfix
3. You're right this repo isn't using the git tags, though do be aware that `npm version` does make a git tag commit. 
4. the user account info is in the passwords repo: https://github.com/zooniverse/Production/tree/master/passwords

**Pull request merged**
